# Generated by Django 4.2.7 on 2025-06-02 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('content', models.JSONField(default=dict, verbose_name='Contenido')),
                ('category', models.CharField(choices=[('académico', 'Académico'), ('ejecutivo', 'Ejecutivo'), ('investigación', 'Investigación'), ('estadístico', 'Estadístico'), ('evaluación', 'Evaluación'), ('digital', 'Digital'), ('personalizada', 'Personalizada')], default='académico', max_length=50)),
                ('template_type', models.CharField(choices=[('report', 'Reporte'), ('document', 'Documento'), ('presentation', 'Presentación'), ('form', 'Formulario')], default='report', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variable_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('boolean', 'Booleano'), ('list', 'Lista')], max_length=50)),
                ('default_value', models.JSONField(blank=True, default=dict)),
                ('is_required', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='templates.template')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('section_type', models.CharField(choices=[('text', 'Texto'), ('heading', 'Encabezado'), ('list', 'Lista'), ('table', 'Tabla'), ('chart', 'Gráfico'), ('image', 'Imagen')], default='text', max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('is_expanded', models.BooleanField(default=True)),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='templates.templatesection')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='templates.template')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('text', 'Texto'), ('heading1', 'Título 1'), ('heading2', 'Título 2'), ('list', 'Lista'), ('chart', 'Gráfico'), ('table', 'Tabla'), ('image', 'Imagen')], max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='templates.templatesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
